Expand build deps and add retry on failure

diff --git a/.github/workflows/build-openwrt-router.yml b/.github/workflows/build-openwrt-router.yml
--- a/.github/workflows/build-openwrt-router.yml
+++ b/.github/workflows/build-openwrt-router.yml
@@ -145,9 +145,15 @@ jobs:
           echo "::group::Install buildsystem"
           sudo apt-get update -qq
           sudo apt-get install -y -qq \
-            build-essential clang flex bison g++ gawk \
-            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
-            python3-setuptools rsync swig unzip zlib1g-dev file wget ccache \
+            build-essential clang flex bison cmake g++ gawk \
+            gcc-multilib g++-multilib gettext git libfuse-dev libncurses5-dev libssl-dev \
+            python3 python3-pip python3-ply python3-pyelftools python3-setuptools \
+            rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake \
+            curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp \
+            texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint \
+            antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename \
+            qemu-utils dos2unix jq python3-netifaces libdw-dev libbz2-dev liblzma-dev \
+            libzstd-dev \
             > /dev/null 2>&1
           echo "::endgroup::"
 
@@ -314,6 +320,8 @@ jobs:
           echo "::endgroup::"
 
       - name: Build everything
+        id: build_everything
+        continue-on-error: true
         working-directory: openwrt
         run: |
           echo "::group::Build everything"
@@ -321,6 +329,24 @@ jobs:
           make -j$(nproc) 2>/dev/null || make V=s
           date +"%Y-%m-%d %H:%M:%S %Z"
           echo "::endgroup::"
+
+      - name: Verbose Retry on Build Failure
+        id: verbose_retry
+        if: steps.build_everything.outcome == 'failure'
+        continue-on-error: true
+        working-directory: openwrt
+        run: |
+          echo "::group::Verbose Retry on Build Failure"
+          date +"%Y-%m-%d %H:%M:%S %Z"
+          make -j1 V=s
+          date +"%Y-%m-%d %H:%M:%S %Z"
+          echo "::endgroup::"
+
+      - name: Fail Workflow if Build Failed
+        if: steps.build_everything.outcome == 'failure' && steps.verbose_retry.outcome != 'success'
+        run: |
+          echo "Build failed in both normal and verbose retry."
+          exit 1
 
       - name: Clean ccache cache
         continue-on-error: true
